### ISSUE TITLE
Code Editor

### ISSUE THREAD

**Issue by HittmanA** [Newawe/code-editor#2]
Hello @bjskistad ?

**Comment by bjskistad** [comment]
Hiya.

**Comment by HittmanA** [comment]
Hey! Im gonna deleted then open a new repo so I can upload the code.

**Comment by HittmanA** [comment]
Ok?

**Comment by HittmanA** [comment]
Ok?

**Comment by bjskistad** [comment]
Ok...

**Comment by HittmanA** [comment]
I can't add anything to the repo, it won't let me, so I have to make the repo myself. Ill do it on newawe.
